# Generated by Django 2.1.7 on 2019-03-30 14:55

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ctype', models.IntegerField(choices=[(0, 'unknown'), (1, 'good'), (2, 'bad')])),
                ('desc', models.TextField()),
            ],
            bases=(models.Model, utils.models.AuditMixin),
        ),
    ]
