# Generated by Django 2.1.7 on 2019-04-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='company',
            name='homepage',
            field=models.URLField(blank=True, null=True, verbose_name='链接'),
        ),
    ]
