# Generated by Django 2.1.7 on 2019-04-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190409_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='company',
            name='ctype',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'good'), (2, 'bad')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='company',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='company',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='证据'),
        ),
        migrations.AlterField(
            model_name='company',
            name='homepage',
            field=models.URLField(blank=True, null=True, verbose_name='主页链接'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
    ]
